import type { Comment, Post } from './types'

const authors = {
  maya: {
    name: 'Maya Chen',
    role: 'Computer Science · Class of 2025',
    avatar: 'https://i.pravatar.cc/160?img=47',
    bio: 'Maya writes about humane technology, creative coding, and the small systems that make student life work better.',
  },
  arjun: {
    name: 'Arjun Mehta',
    role: 'Full-stack developer & open source maintainer',
    avatar: 'https://i.pravatar.cc/160?img=12',
    bio: 'Arjun builds tools for developers and thinks in public about the craft behind reliable software.',
  },
  elena: {
    name: 'Elena Rossi',
    role: 'Interaction designer · Design Society',
    avatar: 'https://i.pravatar.cc/160?img=32',
    bio: 'Elena is interested in the space between a useful interface and one that feels genuinely considerate.',
  },
  noah: {
    name: 'Noah Williams',
    role: 'Systems engineering student & tinkerer',
    avatar: 'https://i.pravatar.cc/160?img=68',
    bio: 'Noah documents experiments, hardware projects, and the lessons that only show up when a deadline is close.',
  },
  sara: {
    name: 'Sara Okafor',
    role: 'Product engineering intern',
    avatar: 'https://i.pravatar.cc/160?img=44',
    bio: 'Sara writes at the intersection of early careers, product thinking, and building a sustainable creative practice.',
  },
}

const images = {
  neural: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85',
  desk: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=85',
  code: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=85',
  interface: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=85',
  books: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1200&q=85',
  network: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=85',
  workshop: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=85',
  city: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85',
  notes: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1200&q=85',
  hardware: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85',
  type: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=1200&q=85',
  stage: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=85',
}

export const categories = ['AI & Society', 'Engineering', 'Design', 'Open Source', 'College Life', 'Careers', 'Productivity']

export const seedPosts: Post[] = [
  {
    id: 'the-small-model-revolution',
    title: 'The small model revolution is a design problem',
    subtitle: 'What happens when intelligence moves from the cloud into every object we use?',
    excerpt: 'The next wave of AI will not arrive as a bigger chat window. It will arrive quietly, inside the tools we already know how to use.',
    coverImage: images.neural,
    category: 'AI & Society',
    tags: ['AI', 'Machine Learning', 'Design'],
    author: authors.maya,
    date: '2024-11-28',
    readingTime: 7,
    likes: 284,
    status: 'published',
    featured: true,
    content: [
      { type: 'paragraph', text: 'For the last two years, the most visible story in artificial intelligence has been scale. Bigger models, longer context windows, more parameters, more compute. But a quieter shift is now taking shape at the other end of the spectrum: models small enough to run locally, privately, and often invisibly.' },
      { type: 'paragraph', text: 'That shift is usually described as an engineering achievement. It is one. Yet the more interesting question is what it asks of the people designing the products around it. When intelligence leaves the browser tab and enters a camera, a keyboard, or a pair of headphones, the interface is no longer a prompt box. It is the object itself.' },
      { type: 'heading', text: 'Ambient intelligence needs a point of view' },
      { type: 'paragraph', text: 'A small model cannot know everything, and that is precisely the reason to design with it rather than around it. Its limitations make the product team decide what matters locally: a vocabulary, a gesture, a moment of interruption, a clear boundary around what is never sent away.' },
      { type: 'quote', text: 'The best local AI will feel less like a genius in the room and more like a considerate tool on the desk.' },
      { type: 'paragraph', text: 'For students building prototypes, this is a useful constraint. Start with the moment, not the model. Ask what should happen in three seconds when the network is unavailable. Ask how the user can tell what the system heard, what it inferred, and where it might be wrong.' },
      { type: 'heading', text: 'A smaller canvas can make better products' },
      { type: 'paragraph', text: 'The most exciting AI interfaces of the next year may have almost no visible AI surface at all. They will be deliberate about attention, honest about uncertainty, and specific about the work they help someone complete. That is not a limitation of the technology. It is a chance to make the technology feel human-sized.' },
    ],
  },
  {
    id: 'shipping-without-a-framework',
    title: 'Shipping a side project without losing the plot',
    subtitle: 'A practical field guide to choosing constraints, keeping momentum, and knowing when to stop polishing.',
    excerpt: 'The fastest way to finish a project is rarely to move faster. It is to decide what the project is actually for.',
    coverImage: images.desk,
    category: 'Productivity',
    tags: ['Building', 'Focus', 'Students'],
    author: authors.sara,
    date: '2024-11-24',
    readingTime: 6,
    likes: 191,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'Every student developer has a folder full of almost-projects. A half-built habit tracker, a clever browser extension, an app that was going to make group projects bearable. The problem is usually not a lack of energy. It is a lack of a finish line small enough to see.' },
      { type: 'heading', text: 'Write the one-sentence promise' },
      { type: 'paragraph', text: 'Before choosing a framework or sketching a logo, write the sentence a user should be able to say after using your project. “I can find my lab partner’s notes in under a minute” is a promise. “A smarter campus platform” is an aspiration.' },
      { type: 'paragraph', text: 'This sentence becomes a surprisingly good filter. If a feature does not make the promise more believable, it goes into a later list. Later lists are not failures. They are how you protect the thing you came to make.' },
      { type: 'list', text: 'A good first version usually has:', items: ['One person it is for', 'One repeated problem', 'One path from input to useful output', 'One way to tell if it worked'] },
      { type: 'paragraph', text: 'A project is finished when its core loop can survive contact with another person. Not when every corner is elegant. Get it into someone else’s hands while the decisions are still cheap to change.' },
    ],
  },
  {
    id: 'css-is-a-material',
    title: 'CSS is a material, not a layer',
    subtitle: 'The web gets more interesting when we treat layout as a medium with its own grain and constraints.',
    excerpt: 'Good frontend work is not decoration applied to a wireframe. It is the careful shaping of space, rhythm, and meaning.',
    coverImage: images.interface,
    category: 'Design',
    tags: ['CSS', 'Frontend', 'Design Systems'],
    author: authors.elena,
    date: '2024-11-20',
    readingTime: 5,
    likes: 236,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'There is a familiar handoff ritual in digital product teams: design supplies the picture, engineering supplies the behavior, and CSS is asked to make the two agree. The ritual is convenient, but it makes the browser feel like a rendering machine instead of a medium.' },
      { type: 'paragraph', text: 'A material has qualities you learn by working with it. Paper folds. Wood has a grain. The web reflows, stretches, waits, and responds to an input method you do not control. Its constraints are not annoyances to hide; they are where the character comes from.' },
      { type: 'heading', text: 'Let the content set the rhythm' },
      { type: 'paragraph', text: 'The strongest CSS systems I have worked with began with editorial questions. How long can this headline be before the page loses its voice? Where does a reader pause? Which edges need to align, and which can drift? A spacing scale is useful, but it becomes a design language only when it follows a reason.' },
      { type: 'quote', text: 'Responsive design is not a shrinking exercise. It is a practice of deciding what deserves to remain.' },
      { type: 'paragraph', text: 'Build components that can change their mind. Use a grid as an invitation, not a cage. If a layout only works at the screenshot width, it has not been designed yet.' },
    ],
  },
  {
    id: 'maintainers-after-midnight',
    title: 'What maintainers do after midnight',
    subtitle: 'Open source is built in public, but the hardest decisions often happen in the quiet hours.',
    excerpt: 'Behind every dependable package is a trail of patient choices about scope, documentation, and people.',
    coverImage: images.code,
    category: 'Open Source',
    tags: ['Open Source', 'Community', 'Software'],
    author: authors.arjun,
    date: '2024-11-16',
    readingTime: 8,
    likes: 318,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'The romantic image of open source is a terminal glowing in the dark and a breakthrough committed before breakfast. The lived version is more ordinary: a maintainer reading the same issue three times, trying to tell whether a bug is real, a documentation gap, or a mismatch of expectations.' },
      { type: 'heading', text: 'Reliability is a social feature' },
      { type: 'paragraph', text: 'A project becomes dependable through a sequence of small invitations. A clear readme. A useful error message. A contribution guide that assumes good intent without assuming prior knowledge. These are not peripheral tasks. They are the interface between a codebase and everyone who will carry it forward.' },
      { type: 'paragraph', text: 'The best maintainers I know are not the fastest typists in the room. They are good editors. They remove options when too many choices create confusion. They name trade-offs so the next person does not have to rediscover them.' },
      { type: 'list', text: 'Before opening a new issue, try:', items: ['Reproducing the smallest possible case', 'Searching the changelog and existing discussions', 'Describing the expected behavior in one sentence', 'Including what you already tried'] },
      { type: 'paragraph', text: 'That small amount of care is what makes a public project feel like a place rather than a pile of files.' },
    ],
  },
  {
    id: 'the-cafeteria-as-studio',
    title: 'The cafeteria as studio',
    subtitle: 'Notes on finding a creative practice between lectures, queues, and the noise of campus.',
    excerpt: 'You do not need a perfect studio to make thoughtful work. You need a recurring place where your attention knows how to return.',
    coverImage: images.books,
    category: 'College Life',
    tags: ['Campus', 'Creative Practice', 'Life'],
    author: authors.maya,
    date: '2024-11-12',
    readingTime: 4,
    likes: 154,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'My best ideas from this semester were written next to a tray of tea, between a statistics lecture and a club meeting. The cafeteria was too loud for deep work and too public for perfection. That turned out to be exactly the point.' },
      { type: 'paragraph', text: 'A recurring, imperfect place lowers the ceremony around beginning. There is no setup to perform. Open the notebook, write the date, continue the thought from yesterday. The work becomes less about waiting for the right mood and more about keeping a promise to your future self.' },
      { type: 'heading', text: 'Leave evidence for the next you' },
      { type: 'paragraph', text: 'When time is fragmented, a project needs breadcrumbs. End a session by writing what changed, what is unresolved, and the smallest next action. It takes two minutes and can save twenty minutes of trying to remember who you were when you stopped.' },
      { type: 'quote', text: 'A practice does not need ideal conditions. It needs a door you can open again.' },
    ],
  },
  {
    id: 'your-first-technical-interview',
    title: 'Your first technical interview is a design problem',
    subtitle: 'Preparation is not about performing certainty. It is about making your thinking easy to follow.',
    excerpt: 'The strongest candidates do not hide the messy middle. They give the interviewer a map of how they are reasoning.',
    coverImage: images.city,
    category: 'Careers',
    tags: ['Careers', 'Interviews', 'Communication'],
    author: authors.sara,
    date: '2024-11-08',
    readingTime: 7,
    likes: 267,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'Technical interviews are often framed as a test of recall: can you produce the right algorithm under pressure? In practice, the signal is closer to collaboration. Can another person understand your assumptions, follow your choices, and help when the path gets uncertain?' },
      { type: 'heading', text: 'Make your reasoning visible' },
      { type: 'paragraph', text: 'Start by restating the problem. Ask what the inputs look like and what constraints matter. Say what you are optimizing for before you reach for a data structure. These moves are not filler; they turn a private chain of thoughts into a shared working surface.' },
      { type: 'paragraph', text: 'When you get stuck, name the branch you are on. “I can solve this with a nested loop, then I will look for a way to reduce the repeated work.” That sentence shows progress even before the final insight arrives.' },
      { type: 'list', text: 'A useful practice loop:', items: ['Explain the problem without code', 'Solve the clear version first', 'Test with a tiny example out loud', 'Reflect on one trade-off, not every trade-off'] },
      { type: 'paragraph', text: 'You are not trying to look like someone who never gets stuck. You are showing that you know how to keep moving when you do.' },
    ],
  },
  {
    id: 'a-hackathon-is-a-short-story',
    title: 'A hackathon is a short story',
    subtitle: 'How to give a weekend project a beginning, middle, and ending people can remember.',
    excerpt: 'The demo is not a report of everything you built. It is a carefully edited argument for why the work matters.',
    coverImage: images.stage,
    category: 'Engineering',
    tags: ['Hackathons', 'Teams', 'Presentations'],
    author: authors.noah,
    date: '2024-11-02',
    readingTime: 5,
    likes: 204,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'A good hackathon project rarely wins because it has the most features. It wins because the room understands the problem, sees the turn, and remembers the feeling of the ending.' },
      { type: 'heading', text: 'Choose the moment of change' },
      { type: 'paragraph', text: 'Start with the before. Show the awkward spreadsheet, the confusing form, the ten minutes someone loses every week. Then make the change visible. A demo should let an audience feel the distance between those two moments.' },
      { type: 'paragraph', text: 'This narrative also helps teams make decisions. If a feature does not make the before-and-after clearer, it may be a good feature for later and a bad feature for this weekend.' },
      { type: 'quote', text: 'The best demo is a product decision with a beginning and an ending.' },
    ],
  },
  {
    id: 'the-case-for-boring-infrastructure',
    title: 'The case for boring infrastructure',
    subtitle: 'A quiet system is not an unambitious one. It is a promise that the product can keep making.',
    excerpt: 'There is dignity in choosing tools that disappear into the work.',
    coverImage: images.network,
    category: 'Engineering',
    tags: ['Infrastructure', 'Systems', 'Reliability'],
    author: authors.arjun,
    date: '2024-10-26',
    readingTime: 6,
    likes: 176,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'In a culture that rewards novelty, infrastructure can feel like a place to prove ambition. But the most valuable systems are often the ones that make no demand on the people using them. They are predictable, documented, and slightly boring in the best possible way.' },
      { type: 'paragraph', text: 'Boring does not mean static. It means the change has a reason, a rollback, and a place in the story of the system. It means the team can spend its energy on the product instead of negotiating with its foundations.' },
      { type: 'heading', text: 'Reliability creates room for taste' },
      { type: 'paragraph', text: 'When the underlying system is stable, design and product decisions can become more specific. You can tune a detail because you trust the rest of the surface. Reliability is not separate from craft; it is what lets craft accumulate.' },
    ],
  },
  {
    id: 'learning-to-read-code',
    title: 'Learning to read code before writing it',
    subtitle: 'The underrated engineering skill that makes every unfamiliar repository less intimidating.',
    excerpt: 'You do not need to understand every file to make a useful map of a codebase.',
    coverImage: images.notes,
    category: 'Engineering',
    tags: ['Learning', 'Code', 'Mentorship'],
    author: authors.noah,
    date: '2024-10-18',
    readingTime: 6,
    likes: 229,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'When a new repository feels overwhelming, it is tempting to start by reading everything. That is like learning a city by memorizing every address. A better first move is to learn its landmarks: where data enters, where decisions happen, and where the result leaves the system.' },
      { type: 'heading', text: 'Trace one user action' },
      { type: 'paragraph', text: 'Pick one visible action and follow it inward. Find the button, the handler, the request, the state change, and the UI that reflects it. You will not understand the whole architecture, but you will have a thread to pull the next time a name looks unfamiliar.' },
      { type: 'list', text: 'Questions worth asking while reading:', items: ['What is the source of truth?', 'Where are errors turned into user language?', 'Which decisions are local to this file?', 'What would break if this value were missing?'] },
      { type: 'paragraph', text: 'Reading code is an act of building a mental model. The model can be incomplete and still be useful. In fact, it has to be incomplete if you want to keep learning.' },
    ],
  },
  {
    id: 'the-interface-between-classes',
    title: 'The interface between classes',
    subtitle: 'What student communities teach us about building products people actually return to.',
    excerpt: 'A campus is a dense network of small rituals. The best tools respect those rituals instead of trying to replace them.',
    coverImage: images.workshop,
    category: 'College Life',
    tags: ['Community', 'Product', 'Campus'],
    author: authors.elena,
    date: '2024-10-11',
    readingTime: 5,
    likes: 138,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'The most useful student products I have seen did not begin by trying to make campus more efficient. They began with an existing ritual: a club meeting, a shared drive, a message sent before a deadline, a friend asking if anyone had a charger.' },
      { type: 'paragraph', text: 'These rituals have texture. They include hesitation, shorthand, and a surprising amount of trust. A product that fits has to learn that texture before it tries to smooth anything out.' },
      { type: 'heading', text: 'Design for the handoff' },
      { type: 'paragraph', text: 'Student life is full of handoffs. One person starts the document, another finishes the slides, someone else knows the room number. Tools become valuable when they make those transitions legible without adding ceremony.' },
      { type: 'quote', text: 'Good community software does not make people feel managed. It makes participation feel easier.' },
    ],
  },
  {
    id: 'a-little-more-human',
    title: 'A little more human than necessary',
    subtitle: 'Why the details that look inefficient often make technology feel worth using.',
    excerpt: 'The most memorable interfaces leave room for recognition, surprise, and a person’s way of doing things.',
    coverImage: images.type,
    category: 'Design',
    tags: ['Human-centered', 'Interfaces', 'Craft'],
    author: authors.maya,
    date: '2024-10-04',
    readingTime: 5,
    likes: 249,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'Efficiency is a useful measure, but it is a poor north star on its own. A product can remove every unnecessary click and still feel strangely difficult to love. The difference is often in the small details that do not optimize a funnel.' },
      { type: 'paragraph', text: 'A thoughtful empty state. A status that tells the truth. A name remembered in the right place. These gestures are not decoration. They tell the user that the system knows it is sharing their time.' },
      { type: 'heading', text: 'The cost of being generic' },
      { type: 'paragraph', text: 'When every edge is rounded and every message is smoothed into the same polite tone, a product loses its point of view. Personality is not noise added after usability. It is the feeling that the decisions belong together.' },
      { type: 'paragraph', text: 'Build the useful thing. Then give it one or two details that could only have come from someone paying attention.' },
    ],
  },
  {
    id: 'building-a-better-lab-notebook',
    title: 'Building a better lab notebook',
    subtitle: 'A lightweight system for recording experiments so failed ideas still return something useful.',
    excerpt: 'The point of a lab notebook is not to prove that you were right. It is to make the next attempt smarter.',
    coverImage: images.hardware,
    category: 'Productivity',
    tags: ['Experiments', 'Research', 'Notes'],
    author: authors.noah,
    date: '2024-09-28',
    readingTime: 4,
    likes: 121,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'A project journal becomes valuable when it can hold a wrong idea without turning it into a small embarrassment. The goal is not a polished timeline. It is a record detailed enough that future you can distinguish a bad idea from a badly tested one.' },
      { type: 'list', text: 'For every experiment, record:', items: ['What you expected', 'What you changed', 'What happened', 'What you will try next'] },
      { type: 'paragraph', text: 'That final line is the difference between a diary and a tool. It keeps the work moving, even when the result is a dead end.' },
      { type: 'paragraph', text: 'The best notebook is the one you will actually open. Keep the format light enough to use on a tired afternoon, and specific enough to rescue you a month later.' },
    ],
  },
  {
    id: 'the-work-after-the-win',
    title: 'The work after the win',
    subtitle: 'A note for the moment after a showcase, a scholarship, or a project finally ships.',
    excerpt: 'Recognition can open a door. The next season is about deciding what you want to carry through it.',
    coverImage: images.stage,
    category: 'Careers',
    tags: ['Growth', 'Careers', 'Reflection'],
    author: authors.sara,
    date: '2024-09-19',
    readingTime: 4,
    likes: 189,
    status: 'published',
    content: [
      { type: 'paragraph', text: 'A win changes the questions around you. People want to know what is next, and it is easy to mistake their curiosity for an obligation to immediately become a larger version of yourself.' },
      { type: 'paragraph', text: 'Take a little time to name what the project actually taught you. Which part would you repeat? Which part only worked because the deadline was close? What kind of work made you lose track of time for the right reasons?' },
      { type: 'heading', text: 'Keep the evidence, not just the applause' },
      { type: 'paragraph', text: 'Save the screenshots, the rough notes, the message from the teammate who made the hard week lighter. A portfolio can show the outcome. Your own archive should remember the process.' },
      { type: 'quote', text: 'The next chapter does not have to be a bigger stage. It can be a better fit.' },
    ],
  },
  {
    id: 'notes-from-the-edge-of-the-map',
    title: 'Notes from the edge of the map',
    subtitle: 'An unfinished field note on building a campus tool that starts with listening.',
    excerpt: 'The first version is still taking shape. These are the questions guiding it there.',
    coverImage: images.notes,
    category: 'College Life',
    tags: ['Campus', 'Building', 'Work in progress'],
    author: { name: 'Alex Morgan', role: 'Technical department contributor', avatar: 'https://i.pravatar.cc/160?img=49', bio: 'Alex is a student builder exploring the edges between technology and everyday life.' },
    date: '2024-11-30',
    readingTime: 4,
    likes: 0,
    status: 'draft',
    content: [
      { type: 'paragraph', text: 'There are still more questions than screens. That feels like the right place to be for now.' },
      { type: 'paragraph', text: 'The next version starts with a conversation, not a component.' },
    ],
  },
]

export const seedComments: Comment[] = [
  { id: 'comment-1', postId: 'the-small-model-revolution', author: 'Priya Nair', avatar: 'https://i.pravatar.cc/80?img=25', body: 'The distinction between a prompt box and the object itself is such a useful way to think about this. I’m bookmarking the paragraph on constraints.', date: '2 days ago' },
  { id: 'comment-2', postId: 'the-small-model-revolution', author: 'Jon Bell', avatar: 'https://i.pravatar.cc/80?img=11', body: 'This makes me want to prototype the offline version first, rather than treating it as a fallback.', date: '1 day ago' },
  { id: 'comment-3', postId: 'maintainers-after-midnight', author: 'Luca P.', avatar: 'https://i.pravatar.cc/80?img=60', body: '“They are good editors” is exactly it. Maintaining is mostly making the next decision easier for someone else.', date: '6 days ago' },
]
